# -*- mode: ruby -*-
# vi: set ft=ruby :

# The VMs are using the Flatcar distribution provided by : https://github.com/obourdon/flatcar-packer-vbox

Vagrant.configure("2") do |config|
  servers=[
    {
      :hostname => "Node1",
      :box => "obourdon/flatcar-linux-observability",
      :box_version => "2905.2.0",
      :ip => "172.16.0.2",
      :ssh_port => '2200',
    },
    {
      :hostname => "Node2",
      :box => "obourdon/flatcar-linux-observability",
      :box_version => "2905.2.0",
      :ip => "172.16.0.3",
      :ssh_port => '2201',
    },
    {
      :hostname => "Node3",
      :box => "obourdon/flatcar-linux-observability",
      :box_version => "2905.2.0",
      :ip => "172.16.0.4",
      :ssh_port => '2202',
    },
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = machine[:box]
      node.vm.box_version = machine[:box_version]
      node.vm.hostname = machine[:hostname]
      node.vm.network :private_network, ip: machine[:ip]
      node.vm.network "forwarded_port", guest: 22, host: machine[:ssh_port], id: "ssh"

      node.vm.provision "shell" do |s|
        s.path = "./execConsulClientServer.sh"
        s.args = machine[:server] ? [machine[:ip]] : [machine[:ip], "172.16.0.2"]
        s.privileged = true
      end

      node.vm.provision "shell" do |s|
        s.path = "./execNomadClientServer.sh"
        s.args = machine[:server] ? [machine[:ip]] : [machine[:ip], "172.16.0.2"]
        s.privileged = true
      end

      # node.vm.synced_folder "../jobs/", "/jobs"

      node.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 2048]
        vb.customize ["modifyvm", :id, "--cpus", 1]
      end
    end
  end
end
